services:
  analitica-api:
    build: .
    image: pharmavida_analitica:latest
    container_name: pharmavida_analitica
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws:ro
    environment:
      - PYTHONPATH=/app