services:
  # Node.js/Express Backend Service
  recetas-api:
    build: .
    image: pharmavida_recetas
    container_name: pharmavida_recetas
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ~/.aws:/home/nodejs/.aws:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/echo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
