services:
  # Spring Boot Backend Service
  usuarios-api:
    build: .
    image: pharmavida_usuarios
    container_name: pharmavida_usuarios
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      # Java Options
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s