version: '3.8'

services:
  django-backend:
    build: .
    container_name: django_backend
    env_file:
      - .env
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/echo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s